controllers/ClassificationController.php
<?php

namespace app\controllers;

use Yii;
use app\models\CarType;
use app\models\Subject;
use app\models\Special;

class ClassificationController extends Controller
{
    /**
     * actionIndex() 显示首页
     *
     * @return string
     */
    public function actionIndex()
    {
        // 接收参数
        $intCarId = Yii::$app->request->get('id', 1) ?: 1;   // 车型ID

        // 查询车型信息、没有数据直接返回
        if (!$car = CarType::findOne($intCarId)) {
            return $this->errorRedirect('分类信息不存在');
        }

        // 查询科目
        $subject = Subject::findAll(['status' => 1, 'car_id' => $car->id]);
        $special = Special::findOne(['name' => '难题']);
        return $this->render('index', compact('special', 'subject', 'car'));
    }

    /**
     * 章节信息
     * 
     * @param $id
     *
     * @return mixed|string
     */
    public function actionSubject($id)
    {
        $id = $id ? intval($id) : 1;
        // 查询平台信息，没有数据直接返回
        if (!$subject = Subject::findOne($id)) {
            return $this->errorRedirect('章节信息不存在');
        }

        $cars    = $subject->car;
        $special = Special::findOne(['name' => '难题']);
        return $this->render('subject', compact('cars', 'subject', 'special'));
    }
}

controllers/QuestionController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Subject;
use app\models\UserCollect;
use jinxing\admin\traits\JsonTrait;
use app\models\Question;
use app\models\Chapter;
use app\models\Special;
use yii\helpers\ArrayHelper;
use yii\helpers\Json;
use yii\helpers\Url;

/**
 * Class QuestionController 题库信息
 *
 * @package app\controllers
 */
class QuestionController extends Controller
{
    use JsonTrait;

    /**
     * actionIndex() 显示首页
     */
    public function actionIndex()
    {
        // 接收参数
        $request   = Yii::$app->request;
        $subjectId = (int)$request->get('subject', 1) ?: 1;       // 科目ID
        $type      = $request->get('type', 'all');                // 类型 chapter and special and null
        $cid       = (int)$request->get('cid');                               // 对应类型子类ID
        $style     = $request->get('style', 'sequence');          // 答题类型 sequence 顺序 and random 随机

        // 查询科目, 有问题抛出错误
        if (!$subject = Subject::findOne($subjectId)) {
            return $this->errorRedirect('科目信息不存在');
        }

        $cars   = $subject->car;
        $crumbs = [
            [
                'label' => $cars->name,
                'url'   => Url::toRoute(['classification/index', 'id' => $cars->id])
            ],
            [
                'label' => $subject->name,
                'url'   => Url::toRoute(['classification/subject', 'id' => $subject->id]),
            ]
        ];

        $where = [
            'status'     => Question::STATUS_KEY,
            'subject_id' => $subject->id
        ];

        // 全部题目
        $allTotal = (int)Question::find()->where($where)->count(); // 全部题库

        // 根据类型查询数据
        switch ($type) {
            case 'chapter':
                $where['chapter_id'] = $cid;
                $chapter             = Chapter::findOne($cid);
                $crumbs[]            = ['label' => $chapter ? $chapter->name : '', 'url' => Url::toRoute(['question/chapter'])];
                break;
            case 'special':
                $where['special_id'] = $cid;
                $special             = Special::findOne($cid);
                $crumbs[]            = ['label' => $special ? $special->name : '', 'url' => Url::toRoute(['question/special'])];
                break;
        }

        $crumbs[]                              = $style == 'sequence' ? '顺序练习' : '随机练习';
        Yii::$app->view->params['breadcrumbs'] = $crumbs;

        // 查询一条数据
        if (!$question = Question::findOne($where)) {
            return $this->errorRedirect('问题不存在');
        }

        // 开始查询
        $total = (int)Question::find()->where($where)->count();
        $ids   = Question::getAllIds($where);
        if ($style == 'random') {
            shuffle($ids);
        }

        // 查询问题答案
        $answer = Json::decode($question->answers);
        return $this->render('index', [
            'cars'       => $cars, // 车型信息
            'subject'    => $subject,
            'allTotal'   => $allTotal,
            'total'      => $total,
            'hasCollect' => UserCollect::hasCollect($question->id, $subject->id),
            'allIds'     => Json::encode($ids),
            'question'   => $question,
            'answer'     => $answer,
            'style'      => $style,
            'type'       => $type
        ]);
    }

    /**
     * actionChapter() 章节练习
     * @return string
     * @throws \yii\db\Exception
     */
    public function actionChapter()
    {
        // 查询科目信息
        if (!$subject = Subject::findOne(Yii::$app->request->get('subject', 1))) {
            return $this->errorRedirect('章节练习问题信息为空');
        }

        if (!$chapter = $subject->chapters) {
            return $this->errorRedirect('章节练习问题信息为空');
        }

        $chapterIds = ArrayHelper::getColumn($chapter, 'id');
        if ($counts = Yii::$app->db->createCommand('SELECT 
                  COUNT(*) AS `length`, 
                  `chapter_id` 
              FROM `ks_question` 
              WHERE `chapter_id` IN (' . implode(',', $chapterIds) . ') 
              GROUP BY `chapter_id`')->queryAll()) {
            $counts = ArrayHelper::map($counts, 'chapter_id', 'length');
        }

        $cars = $subject->car;
        return $this->render('chapter', compact('cars', 'subject', 'chapter', 'counts'));
    }

    /**
     * actionSpecial() 专项练习
     * @return string
     * @throws \yii\db\Exception
     */
    public function actionSpecial()
    {
        // 查询科目信息
        if (!$subject = Subject::findOne(Yii::$app->request->get('subject', 1))) {
            return $this->errorRedirect('专项练习问题不存在');
        }

        $all = $ids = $counts = [];
        if ($special = Special::find()->asArray()->all()) {
            foreach ($special as $value) {
                /* @var $value array */
                $intKid = $value['pid'] == 0 ? $value['id'] : $value['pid'];
                if (!isset($all[$intKid])) {
                    $all[$intKid] = ['child' => []];
                }

                // 父级处理
                if ($value['pid'] == 0) {
                    $all[$intKid] = array_merge($all[$intKid], $value);
                    continue;
                }

                // 字集处理
                $index                         = $value['sort'] . '-' . $value['id'];
                $ids[]                         = (int)$value['id'];
                $all[$intKid]['child'][$index] = $value;
            }

            // 没有数据默认查询
            $ids = $ids ?: [0];
            // 查询
            if ($counts = Yii::$app->db->createCommand('SELECT 
                    COUNT(*) AS `length`, 
                    `special_id` 
                    FROM `ks_question` 
                    WHERE `special_id` IN (' . implode(',', $ids) . ') AND `subject_id` = ' . intval($subject->id) . '  
                    GROUP BY `special_id`')->queryAll()) {
                $counts = ArrayHelper::map($counts, 'special_id', 'length');
            }

            $files = [];
            foreach ($all as $k => &$v) {
                $files[$k] = $v['sort'];
                ksort($v['child']);
            }

            array_multisort($files, SORT_ASC, $all);
        }

        return $this->render('special', [
            'subject' => $subject,
            'cars'    => $subject->car,
            'special' => $all,
            'counts'  => $counts,
        ]);
    }

    /**
     * actionRecord() 记录用户做题信息
     * @return mixed|string
     */
    public function actionRecord()
    {
        $request = Yii::$app->request;
        if (!$intQid = $request->post('qid')) {
            return $this->error();
        }

        $strType = $request->post('sType', 'no');
        if (!$question = Question::findOne($intQid)) {
            return $this->error(220, '没有题目');
        }

        if ($strType == 'no') {
            $cookie = $request->cookies;
            $values = $cookie->get($strType);
            if ($values == null) {
                $values = [$intQid];
            } else {
                $values = Json::decode($values->value, true);
                array_push($values, $intQid);
                $values = array_unique($values);
            }

            // 添加COOKIE
            Yii::$app->response->cookies->add(new \yii\web\Cookie([
                'name'   => $strType,
                'value'  => Json::encode($values),
                'expire' => time() + 86400,
            ]));

            $question->error_number++;
        }

        // 修改记录信息
        $question->do_number++;
        $question->save();
        return $this->success($question);
    }

    /**
     * actionGetQuestion() 获取问题和答案信息
     * @return mixed|string
     */
    public function actionGetQuestion()
    {
        if (!$id = (int)Yii::$app->request->post('qid')) {
            return $this->error(220, '没有题目了');
        }

        if (!$question = Question::findOne($id)) {
            return $this->error(220, '没有题目了');
        }

        return $this->success([
            'hasCollect' => UserCollect::hasCollect($question->id, $question->subject_id),
            'question'   => $question,
            'answers'    => Json::decode($question->answers)
        ]);

    }

    /**
     * actionImitate() 全真模拟考试
     *
     * @return string
     */
    public function actionImitate()
    {
        // 查询科目信息
        if (!$subject = Subject::findOne(Yii::$app->request->get('subject', 1))) {
            return $this->errorRedirect('全真模拟考试问题不存在');
        }

        // 解析配置信息
        $config = Json::decode($subject->config) ?: [];
        $config = array_merge([
            'passingScore'   => 72,
            'totalScore'     => 100,
            'time'           => 60,
            'judgmentScore'  => 2,
            'selectScore'    => 2,
            'multipleScore'  => 3,
            'shortScore'     => 5,
            'judgmentNumber' => 10,
            'selectNumber'   => 40,
            'multipleNumber' => 30,
            'shortNumber'    => 5,
        ], $config);

        // 处理总分
        $config['totalScore'] = $config['shortNumber'] * $config['shortScore'];
        $config['totalScore'] += $config['judgmentNumber'] * $config['judgmentScore'];
        $config['totalScore'] += $config['selectNumber'] * $config['selectScore'];
        $config['totalScore'] += $config['multipleNumber'] * $config['multipleScore'];

        // 默认必须查询条件
        $where = ['subject_id' => $subject->id];

        // 查询所有判断题目
        $where['answer_type'] = Question::ANSWER_TYPE_ONE;
        $arrJudgment          = Question::getAllIds($where);
        $intStart             = mt_rand(0, max(0, count($arrJudgment) - $config['judgmentNumber']));
        $arrJudgment          = array_slice($arrJudgment, $intStart, $config['judgmentNumber']);

        // 查询所以单选题目
        $where['answer_type'] = Question::ANSWER_TYPE_JUDGE;
        $arrSelect            = Question::getAllIds($where);

views/classification/index.php
<?php

use yii\helpers\Url;

$this->title = $car->name.',类型信息';
$this->params['menu'] = [
    'title' => $car->name,
    'link' => Url::toRoute(['index', 'id' => $car->id])
];
$this->registerCssFile('@web/css/index.css', ['depends' => ['app\assets\AppAsset']]);
?>
<div class="page-header">
    <div class="header">
        <h1><?=$car->name?></h1>
        <small>(<?=$car->desc?>)</small>
    </div>
</div>
<?php if ($subject) : ?>
    <div class="block-mnks jkbd-con-item bt4 clearfix">
        <div class="head_nav">
            <h2> 考试科目信息 </h2>
        </div>
        <div class="content-wapper clc col-md-12">
            <?php foreach ($subject as $value): ?>
                <div class="col-md-4">
                    <a class="fl lianxi2-a li0 car-item"  href="<?=Url::toRoute(['classification/subject', 'id' => $value->id])?>">
                        <div class="text-center car-image">
                            <img src="<?=$value->image?>" class="img-responsive"  alt="<?=$value->name?>" />
                        </div>
                        <div class="car-a">
                            <h4><?=$value->name;?></h4>
                        </div>
                    </a>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif; ?>

views/classification/subject.php
<?php

use yii\helpers\Url;

$this->title = $cars->name.','.$subject->name;
$this->registerCssFile('@web/css/index.css', ['depends' => ['app\assets\AppAsset']]);
$this->params['menu'] = [
    'title' => $cars->name,
    'link' => Url::toRoute(['classification/index', 'id' => $cars->id])
];
?>
<div class="page-header">
    <div class="header">
        <h1><?=$cars->name?> - <?=$subject->name?></h1>
        <h2><?=$subject->desc?></h2>
    </div>
</div>

<div class="block-mnks jkbd-con-item bt4">
    <div class="head_nav">
        <h2><?=$subject->name?></h2>
    </div>
    <div class="content-wapper clc col-md-12">
        <div class="col-md-3">
            <a class="fl lianxi2-a li0 lianxi0 col-md-3"  href="<?=Url::toRoute(['question/index', 'subject' => $subject->id, 'style' => 'sequence'])?>">
                <span class="name">顺序练习</span>
            </a>
        </div>
        <div class="col-md-3">
            <a class="fl lianxi2-a li1 lianxi3 col-md-3"  href="<?=Url::toRoute(['question/index', 'subject' => $subject->id, 'style' => 'random'])?>">
                <span class="name">随机练习</span>
            </a>
        </div>
        <div class="col-md-3">
            <a class="fl lianxi2-a li2 lianxichapter col-md-3"  href="<?=Url::toRoute(['question/chapter', 'subject' => $subject->id])?>">
                <span class="name">章节练习</span>
            </a>
        </div>
        <div class="col-md-3">
            <a class="fl lianxi2-a li3 lianxistrengthen col-md-3"  href="<?=Url::toRoute(['question/special', 'subject' => $subject->id,])?>">
                <span class="name">专项练习</span>
            </a>
        </div>
    </div>
    <div class="content-wapper clc col-md-12">
        <div class="col-md-3">
            <a class="fl lianxi2-a li0 lianxi8 col-md-3"  href="<?=Url::toRoute(['question/index', 'subject' => $subject->id, 'type' => 'special', 'cid' => $special ? $special->id : 1])?>">
                <span class="name">难题练习</span>
            </a>
        </div>
        <div class="col-md-3">
            <a class="fl lianxi2-a li1 lianxi5 col-md-3 <?=Yii::$app->user->isGuest ? "is-login login" : "" ?>"  href="<?=Url::toRoute(['user/collect', 'subject' => $subject->id])?>">
                <span class="name">我的收藏</span>
            </a>
        </div>
        <div class="col-md-3">
            <a class="fl lianxi2-a li2 lianxi4 col-md-3"  href="<?=Url::toRoute(['question/warning', 'subject' => $subject->id])?>">
                <span class="name">我的错题</span>
            </a>
        </div>
        <div class="col-md-3">
            <a class="fl lianxi2-a li3 lianxiexam col-md-3"  href="<?=Url::toRoute(['question/imitate', 'subject' => $subject->id])?>">
                <span class="name">全真模拟</span>
            </a>
        </div>
    </div>
</div>