controllers/ClassificationController.php
<?php

namespace app\controllers;

use Yii;
use app\models\CarType;
use app\models\Subject;
use app\models\Special;

class ClassificationController extends Controller
{
    /**
     * actionIndex() 显示首页
     *
     * @return string
     */
    public function actionIndex()
    {
        // 接收参数
        $intCarId = Yii::$app->request->get('id', 1) ?: 1;   // 车型ID

        // 查询车型信息、没有数据直接返回
        if (!$car = CarType::findOne($intCarId)) {
            return $this->errorRedirect('分类信息不存在');
        }

        // 查询科目
        $subject = Subject::findAll(['status' => 1, 'car_id' => $car->id]);
        $special = Special::findOne(['name' => '难题']);
        return $this->render('index', compact('special', 'subject', 'car'));
    }

    /**
     * 章节信息
     * 
     * @param $id
     *
     * @return mixed|string
     */
    public function actionSubject($id)
    {
        $id = $id ? intval($id) : 1;
        // 查询平台信息，没有数据直接返回
        if (!$subject = Subject::findOne($id)) {
            return $this->errorRedirect('章节信息不存在');
        }

        $cars    = $subject->car;
        $special = Special::findOne(['name' => '难题']);
        return $this->render('subject', compact('cars', 'subject', 'special'));
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use jinxing\admin\helpers\Helper;
use jinxing\admin\traits\JsonTrait;
use Yii;
use yii\filters\AccessControl;
use app\models\forms\LoginForm;
use app\models\forms\RegisterForm;
use app\models\User;

/**
 * Site controller
 */
class SiteController extends Controller
{
    use JsonTrait;

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only'  => ['logout', 'register', 'captcha'],
                'rules' => [
                    [
                        'actions' => ['register', 'captcha'],
                        'allow'   => true,
                        'roles'   => ['?'],
                    ],
                    [
                        'actions' => ['logout', 'captcha'],
                        'allow'   => true,
                        'roles'   => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error'   => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class'           => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
                'maxLength'       => 4,           // 最大显示个数
                'minLength'       => 4,           // 最少显示个数
                'padding'         => 5,           // 间距
                'height'          => 38,          // 高度
                'width'           => 130,         // 宽度
                'offset'          => 4,           // 设置字符偏移量 有效果
            ],
        ];
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

    protected function login($message = 'login')
    {
        /* @var $user User */
        $user = Yii::$app->user->identity;
        return $this->success([
            'username' => $user->username,
            'email'    => $user->email,
            'face'     => $user->face,
        ], $message == 'login' ? '登录成功' : '注册成功');
    }

    /**
     * actionLogin() 用户登录
     *
     * @return mixed|string
     */
    public function actionLogin()
    {
        // 用户没有登录
        if (!Yii::$app->user->isGuest) {
            return $this->login();
        }

        $model = new LoginForm();
        if (!$model->load(Yii::$app->request->post(), '') || !$model->login()) {
            return $this->error(1, Helper::arrayToString($model->getErrors()));
        }

        return $this->login();
    }

    /**
     * actionLogout用户退出
     * @return \yii\web\Response
     */
    public function actionLogout()
    {
        // 退出之前修改登录信息
        if ($user = User::findOne(Yii::$app->user->id)) {
            $user->last_time = time();
            $user->last_ip   = Helper::getIpAddress();
            $user->save();
        }

        Yii::$app->user->logout();
        return $this->goHome();
    }

    /**
     * actionRegister() 用户注册
     *
     * @return string|\yii\web\Response
     */
    public function actionRegister()
    {
        // 已经登录
        if (!Yii::$app->user->isGuest) {
            return $this->login();
        }

        // 不是ajax 请求
        if (!Yii::$app->request->isAjax) {
            return $this->error();
        }

        $model = new RegisterForm();
        // 数据加载成功
        if (!$model->load(Yii::$app->request->post(), '')) {
            return $this->error();
        }

        if (!($user = $model->register()) || !Yii::$app->getUser()->login($user)) {
            return $this->error(2, Helper::arrayToString($model->getErrors()));
        }

        return $this->login('registerSuccess');
    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */

/* @var $content string */

use yii\helpers\Html;
use app\assets\AppAsset;
use yii\helpers\Url;
use yii\captcha\Captcha;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title>考试系统 - <?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"> 考试系统 </a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav pull-left">
                <li <?= Yii::$app->controller->id == 'site' && Yii::$app->controller->action->id == 'index' ? 'class="active"' : '' ?>>
                    <a href="/">首页</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false"> 选择考试类型 <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <?php if (isset($this->params['carTypes'])): ?>
                            <?php foreach ($this->params['carTypes'] as $value) : ?>
                                <li>
                                    <a href="<?= Url::toRoute(['classification/index', 'id' => $value->id]) ?>"><?= $value->name ?></a>
                                </li>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    </ul>
                </li>
                <?php if (isset($this->params['menu']) && $this->params['menu']): ?>
                    <li class="active">
                        <a href="<?= $this->params['menu']['link'] ?>"><?= $this->params['menu']['title'] ?></a>
                    </li>
                <?php endif; ?>

                <li><a href="javascript:;" class="login no-login <?= Yii::$app->user->isGuest ? '' : 'hide' ?>">登录</a>
                </li>
                <li><a href="javascript:;"
                       class="register no-login <?= Yii::$app->user->isGuest ? '' : 'hide' ?>">注册</a></li>
                <li class="dropdown user-login <?= Yii::$app->user->isGuest ? 'hide' : '' ?>">
                    <a href="#" class="dropdown-toggle user" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">
                        <img class="nav-user-photo" id="user-face"
                             src="<?= Yii::$app->user->isGuest || !Yii::$app->user->identity->face ? '/images/avatar.jpg' : Yii::$app->user->identity->face ?>"
                             alt="<?= Yii::$app->user->isGuest ? '' : (Yii::$app->user->identity->username ? Yii::$app->user->identity->username : Yii::$app->user->identity->email) ?>">
                        <span class="user-info"><small>Welcome,</small> <span class="text-danger"
                                                                              id="username"><?= Yii::$app->user->isGuest ? '' : (Yii::$app->user->identity->username ? Yii::$app->user->identity->username : Yii::$app->user->identity->email) ?></span></span>
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="dropdown-header"> 我的信息</li>
                        <li><a href="<?= Url::toRoute(['question/warning', 'subject' => 1]) ?>"> 我的错题 </a></li>
                        <li><a href="<?= Url::toRoute(['user/collect', 'subject' => 1]) ?>"> 我的收藏 </a></li>
                        <li role="separator" class="divider"></li>
                        <li class="dropdown-header">其他操作</li>
                        <li><a href="<?= Url::toRoute(['site/logout']) ?>" class=""> 退出登录 </a></li>
                    </ul>
                </li>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>
<div class="container theme-showcase main" id="content" role="main">
    <div class="row">
        <div class="col-md-12">
            <?= $content ?>
        </div>
    </div>
</div> <!-- /container -->

<div class="footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="jkbd-width wid-auto">
                    <ul class="cl">
                        <li>
                            <a href="/" target="_blank" class="a-link">考试系统</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="login-dialog hide member-dialog" id="login-dialog">
    <div>
        <p class="tips normal"> 注册/登录后可保存做题进度 </p>
    </div>
    <div class="content-container">
        <form class="login-form form-horizontal user-form" id="login-form" action="<?= Url::toRoute(['site/login']) ?>">
            <input type="hidden" value="<?= Yii::$app->getRequest()->getCsrfToken() ?>" name="_csrf"/>
            <div class="form-group">
                <input name="username" class="i-username form-control" required="true" rangelength="[2, 100]"
                       placeholder="请输入手机号 or 昵称" type="text"/>
            </div>
            <div class="form-group">
                <input name="password" class="i-password form-control" required="true" rangelength="[6, 50]"
                       placeholder="请输入您的密码" type="password"/>
            </div>
            <div class="form-group">
                <button type="submit" class="submit btn btn-info">登 录</button>
            </div>
            <div class="form-group">
                <span class="show-span pull-left"><a href="javascript:;" class="register">立即注册</a></span>
            </div>
        </form>
    </div>
</div>

<div class="register-dialog member-dialog hide" id="register-dialog">
    <div>
        <p class="tips normal"> 注册/登录后可保存做题进度 </p>
    </div>
    <div class="content-container">
        <form autocomplete="off"
              class="register-form form-horizontal user-form"
              id="register-form"
              action="<?= Url::toRoute(['site/register']) ?>">
            <input type="hidden" value="<?= Yii::$app->getRequest()->getCsrfToken() ?>" name="_csrf"/>
            <div class="form-group">
                <input name="username" class="i-username form-control" required="true" rangelength="[2, 100]"
                       placeholder="请输入昵称" type="text" autocomplete="off">
            </div>
            <div class="form-group">
                <input name="phone" class="i-username form-control" required="true" maxlength="11" minlength="11"
                       placeholder="请输入手机号" type="text">
            </div>
            <div class="form-group">
                <input name="password" id="m-password" class="i-password form-control" required="true"
                       rangelength="[6, 50]" placeholder="请设置密码" type="password" autocomplete="new-password">
            </div>
            <div class="form-group">
                <input name="rePassword" class="i-password form-control" required="true" rangelength="[6, 50]"
                       equalTo="#m-password" placeholder="确认密码" type="password">
            </div>
            <div class="form-group">
                <div class="col-sm-6 pl-none">
                    <input name="verifyCode" class="captchaCode form-control pull-left" required="true" minlength="4"
                           maxlength="6" placeholder="请输入图片验证码" type="text">
                </div>
                <div class="col-sm-6">
                    <?= Captcha::widget([
                        'name'          => 'captchaimg',
                        'captchaAction' => 'site/captcha',
                        'imageOptions'  => [
                            'id'    => 'captchaimg',
                            'title' => '换一个',
                            'alt'   => '换一个',
                            'style' => 'cursor:pointer;margin-left:25px;',
                        ],
                        'template'      => '{image}',
                    ]) ?>
                </div>
            </div>
            <div class="form-group">
                <p class="other-tips">点击“注册”按钮，既表示你同意<a rel="nofollow" target="_blank"
                                                        href="<?= Url::toRoute(['article/detail', 'id' => 1]) ?>">《用户协议》</a>
                </p>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-info submit">立即注册</button>
            </div>
            <div class="form-group">
                <span class="show-span pull-left"><a href="javascript:;" class="login">有账号，去登录</a></span>
            </div>
        </form>
    </div>
</div>
<!--[if !IE]> -->
<script type="text/javascript">
    window.jQuery || document.write("<script src='/js/jquery.min.js'>" + "<" + "/script>");
</script>
<!-- <![endif]-->
<!--[if IE]>
<script type="text/javascript">
    window.jQuery || document.write("<script src='/js/jquery1x.min.js'>" + "<" + "/script>");
</script>
<![endif]-->
<script type="text/javascript">
    if ('ontouchstart' in document.documentElement) document.write("<script src='/js/jquery.mobile.custom.min.js'>" + "<" + "/script>");
</script>
<?php $this->endBody() ?>
<?= $this->blocks['javascript'] ?>
<script>
    var message = '<?=Yii::$app->session->getFlash('error')?>';
    if (message) {
        layer.msg(message);
    }
</script>
</body>
</html>
<?php $this->endPage() ?>