modules/admin/controllers/QuestionController.php
<?php

namespace app\modules\admin\controllers;

use app\models\CarType;
use app\models\Chapter;
use app\models\Question;
use app\models\Special;
use app\models\Subject;
use jinxing\admin\helpers\Helper;
use yii\helpers\ArrayHelper;
use yii\helpers\Json;
use yii;

/**
 * Class QuestionController 题库信息
 *
 * @package app\modules\admin\controllers
 */
class QuestionController extends Controller
{
    /**
     * 使用的model
     */
    public $modelClass = 'app\models\Question';

    /**
     * where() 查询处理
     *
     *
     * @return array 返回数组
     */
    public function where()
    {
        return [
            [['status', 'answer_type', 'subject_id', 'chapter_id', 'special_id'], '='],
        ];
    }

    /**
     * actionIndex() 首页显示
     * @return string
     */
    public function actionIndex()
    {
        // 获取数据
        $special = Special::find()->where(['!=', 'pid', 0])->orderBy('sort')->all();
        $chapter = Chapter::find()->orderBy('sort')->all();
        // 查询考试类型
        $cars = CarType::findAll(['status' => 1]);

        $arrChapter = Helper::map($chapter, 'id', 'name');
        $arrSubject = Subject::getSubject();

        // 专项分类
        $special = Helper::map($special, 'id', 'name');

        return $this->render('index', [
            'cars'        => Json::encode(ArrayHelper::map($cars, 'id', 'name')), // 类型
            'subject'     => Json::encode($arrSubject['subject']), // 科目
            'arrSubject'  => $arrSubject['subject'], // 科目信息,
            'car_subject' => Json::encode($arrSubject['car_subject']),
            'special'     => Json::encode($special), // 专项
            'arrSpecial'  => $special,
            'chapter'     => Json::encode($arrChapter), // 章节
            'arrChapter'  => $arrChapter,
            'status'      => Json::encode(Question::getStatusDesc()),           // 状态
            'color'       => Json::encode(Question::getStatusColor()),           // 状态颜色
            'type'        => Json::encode(Question::getTypeDesc()),               // 答案类型
        ]);
    }

    public function actionCreate()
    {
        $request = \Yii::$app->request;
        if (!$request->isGet && $request->isPost) {
            return parent::actionCreate();
        }

        $intSubject = (int)$request->get('subject_id');
        $intChapter = (int)$request->get('chapter_id');
        if ($intChapter > 0) {
            if ($chapter = Chapter::findOne($intChapter)) {
                $intSubject = $chapter->subject_id;
            } else {
                $intChapter = 0;
            }
        }

        // 查询数据
        $special    = Special::find()->where(['!=', 'pid', 0])->orderBy('sort')->all();
        $chapter    = Chapter::find()->orderBy('sort')->all();
        $chapter[]  = ['id' => 0, 'name' => '请选择'];
        $subject    = Subject::getSubject();
        $subject[0] = '请选择';

        // 载入视图
        return $this->render('create', [
            'subject_id' => $intSubject,
            'chapter_id' => $intChapter,
            'subject'    => $subject,
            'chapter'    => ArrayHelper::map($chapter, 'id', 'name'),
            'types'      => Question::getTypeDesc(),
            'special'    => ArrayHelper::map($special, 'id', 'name'),
        ]);
    }

    /**
     * actionSubject() 获取科目
     * @return mixed|string
     */
    public function actionSubject()
    {
        $request = \Yii::$app->request;
        if (!$request->isAjax || !($intCid = (int)$request->post('cid'))) {
            return $this->error(201);
        }

        return $this->success(Subject::findAll(['status' => 1, 'car_id' => $intCid]));
    }

    /**
     * actionChapter() 获取章节
     *
     * @return mixed|string
     */
    public function actionChapter()
    {
        $request = \Yii::$app->request;
        if (!$request->isAjax || !($intSid = (int)$request->post('sid'))) {
            return $this->error(201);
        }

        return $this->success(Chapter::findAll(['subject_id' => $intSid]));
    }

    /**
     * 处理导入数据
     *
     * @return mixed|string
     * @throws \PHPExcel_Exception
     * @throws \PHPExcel_Reader_Exception
     * @throws yii\db\Exception
     */
    public function actionUploadQuestion()
    {
        // 判断请求方式
        $request = \Yii::$app->request;
        if (!$request->isAjax) {
            return $this->error(201);
        }

        // 接收参数
        $intSubject = (int)$request->post('subject_id');    // 科目信息
        $intChapter = (int)$request->post('chapter_id');    // 章节信息
        $intSpecial = (int)$request->post('special_id');    // 专项信息
        $strFile    = trim($request->post('upload_file'));  // 文件地址

        // 验证提交数据
        if (empty($strFile) || (empty($intSubject) && empty($intChapter))) {
            return $this->error(201);
        }

        // 查询出全部专项信息
        $arrSpecial = Special::find()->where(['!=', 'pid', 0])->indexBy('name')->all();
        if (!$objPHPExcel = \PHPExcel_IOFactory::load('.' . $strFile)) {
            return $this->error(201, '上传文件加载失败');
        }

        $objWorksheet = $objPHPExcel->getActiveSheet();
        $intRows      = $objWorksheet->getHighestRow(); // 获取总行数

        // 读取数据的第二行
        $array  = [];
        $time   = time();
        $fields = [
            'question_title',
            'question_content',
            'answer_type',
            'answers',
            'answer_id',
            'subject_id',
            'chapter_id',
            'created_at',
            'updated_at',
            'special_id',
        ];

        $db = Yii::$app->db;
        for ($i = 2; $i <= $intRows; $i++) {
            // 获取题目类型
            $intAnswerType = (int)$objWorksheet->getCell('C' . $i)->getValue();

            // 获取正确答案信息
            $answer = trim($objWorksheet->getCell('E' . $i)->getValue());
            if ($intAnswerType === Question::ANSWER_TYPE_MULTI) {
                $mixAnswerId = explode(',', $answer);
                $mixAnswerId = array_map(function ($value) {
                    return $value - 1;
                }, $mixAnswerId);
                $mixAnswerId = Json::encode($mixAnswerId);
            } else {
                $mixAnswerId = $answer > 0 ? (int)$answer - 1 : 0;
            }

            // 处理专项信息
            $special = trim($objWorksheet->getCell('F' . $i)->getValue());
            if ($special && isset($arrSpecial[$special])) {
                $special = $arrSpecial[$special]->id;
            } else {
                $special = $intSpecial;
            }

            $array[] = [
                $objWorksheet->getCell('A' . $i)->getValue(),
                $objWorksheet->getCell('B' . $i)->getValue(),
                $intAnswerType,
                Json::encode(explode('|', $objWorksheet->getCell('D' . $i)->getValue())),
                $mixAnswerId,
                $intSubject,
                $intChapter,
                $time,
                $time,
                $special,
            ];

            // 每100条数据新增一次
            if (count($array) >= 100 && $db->createCommand()->batchInsert('{{%question}}', $fields, $array)->execute()) {
                $array = [];
            }
        }

        // 存在数据，并且新增失败、报错误
        if ($array && !$db->createCommand()->batchInsert('{{%question}}', $fields, $array)->execute()) {
            return $this->error(404, '上传题目处理失败');
        }

        return $this->success($array, '上传题目处理成功');
    }
}

modules/admin/controllers/SubjectController.php
<?php

namespace app\modules\admin\controllers;

use app\models\CarType;
use yii\helpers\ArrayHelper;

/**
 * Class SubjectController 科目信息
 *
 * @package app\modules\admin\controllers
 */
class SubjectController extends Controller
{
    /**
     * @var string 使用的 model
     */
    public $modelClass = 'app\models\Subject';

    /**
     * where() 查询处理
     *
     * @return array 返回数组
     */
    public function where()
    {
        return [
            [['id', 'car_id', 'status'], '='],
            ['name', 'like'],
        ];
    }

    public function actionIndex()
    {
        // 查询类别信息
        $carType = CarType::findAll(['status' => 1]);
        $carType = ArrayHelper::map($carType, 'id', 'name');
        return $this->render('index', compact('carType'));
    }
}

modules/admin/views/subject/index.php
<?php

use jinxing\admin\widgets\MeTable;
use \yii\helpers\Json;
use \yii\helpers\Url;

// 定义标题和面包屑信息
$this->title                   = '科目信息';
$this->params['breadcrumbs'][] = $this->title;
?>
<?= MeTable::widget() ?>
<?php $this->beginBlock('javascript') ?>
    <script type="text/javascript">
        var arrConfig = {
            passingScore: "及格分数",
            time: "考试时间(分)",
            judgmentNumber: "判断题数",
            selectNumber: "单选题数",
            multipleNumber: "多选题数",
            shortNumber: "问答题数",
            judgmentScore: "判断题分数",
            selectScore: "单选题分数",
            multipleScore: "多选题分数",
            shortScore: "问答题目分数"
        }, defaultArrConfig = {
            passingScore: 72,
            time: 60,
            judgmentNumber: 10,
            selectNumber: 40,
            multipleNumber: 30,
            shortNumber: 5,
            judgmentScore: 2,
            selectScore: 2,
            multipleScore: 3,
            shortScore: 5
        };

        $.extend(MeTables, {
            configCreate: function (params, defaultConfig) {
                if (!defaultConfig) defaultConfig = defaultArrConfig;
                var html = "<div class='col-sm-12'>";
                for (var x in arrConfig) {
                    html += "<div class='form-group'>" +
                        "<label class='col-sm-3 control-label'>" + arrConfig[x] + "</label>" +
                        "<div class='col-sm-9'>" +
                        "<input type='text' name='" + params.name + "[" + x + "]' required='true' value='" + defaultConfig[x] + "' class='form-control'>" +
                        "</div>" +
                        "</div>";

                }

                return html + "</div>";
            }
        });

        function initConfig(defaultVal) {
            var $div = $(".div-right-config");
            for (var x in defaultVal) {
                $div.find("input[name=config\\[" + x + "\\]]").val(defaultVal[x]);
            }
        }

        var arrCarType = <?=Json::encode($carType)?>,
            arrStatus = <?=Json::encode(Yii::$app->params['status'])?>;
        var myTable = meTables({
            title: "科目信息",
            fileSelector: ["#icon-image"],
            number: false,
            operations: {
                width: "auto",
                buttons: {
                    create: {
                        "className": "btn-success",
                        "cClass": "create-question",
                        "icon": "fa-plus-circle",
                        "sClass": "blue",
                        "button-title": "添加题目"
                    }
                }
            },
            table: {
                columns: [
                    {
                        title: "id",
                        data: "id",
                        edit: {type: "hidden"},
                        search: {type: "text"},
                        defaultOrder: "desc"
                    },
                    {
                        title: "所属类型",
                        data: "car_id",
                        value: arrCarType,
                        edit: {type: "select", required: true, number: true},
                        search: {type: "select"},
                        sortable: false,
                        createdCell: function (td, data) {
                            $(td).html(arrCarType[data] ? arrCarType[data] : data);
                        }
                    },
                    {
                        title: "科目名称",
                        data: "name",
                        sortable: false,
                        edit: {required: true, rangeLength: "[2, 255]"},
                        search: {type: "text"}
                    },
                    {
                        title: "科目说明",
                        data: "desc",
                        edit: {required: true, rangeLength: "[2, 1000]"},
                        sortable: false,
                        isHide: true
                    },
                    {
                        title: "科目配置",
                        data: "config",
                        edit: {type: "config", required: true, rangeLength: "[2, 1000]"},
                        sortable: false,
                        isHide: true
                    },
                    {
                        title: "图标",
                        data: "image",
                        sortable: false,
                        edit: {
                            type: "file",
                            options: {
                                "id": "icon-image",
                                "name": "UploadForm[image]",
                                "input-type": "ace_file",
                                "input-name": "image"
                            }
                        },
                        isHide: true
                    },
                    {
                        title: "排序",
                        data: "sort",
                        edit: {value: 100, required: true, number: true}
                    },
                    {
                        data: "status",
                        title: "状态",
                        value: arrStatus,
                        edit: {type: "radio", default: 1, required: 1, number: 1},
                        search: {type: "select"},
                        createdCell: MeTables.statusString
                    },
                    {
                        title: "创建时间",
                        data: "created_at",
                        createdCell: MeTables.dateTimeString
                    }
                ]
            }
        });

        var $image = null;
        $.extend(myTable, {
            afterShow: function (data) {

                if (this.action !== "delete") {
                    $image.ace_file_input("reset_input");
                    var defaultVal = defaultArrConfig;
                    if (this.action === "update") {
                        // 图片处理
                        if (!empty(data.image)) {
                            $image.ace_file_input("show_file_list", [data.image]);
                        }

                        // 配置文件
                        if (data.config) {
                            try {
                                defaultVal = $.parseJSON(data.config);
                            } catch (e) {

                            }
                        }
                    }

                    console.info("defaultVal", defaultVal);
                    initConfig(defaultVal);
                }

                return true;
            }
        });

        var layerLoading = null;

        function closeLayer() {
            layer.close(layerLoading);
        }

        $(function () {
            myTable.init();
            $image = $("#icon-image");

            // 添加题目
            $(document).on('click', 'button.create-question-show-table', function () {
                var i = $(this).data("row");
                var data = myTable.table.data()[i];
                if (data) {
                    layerLoading = layer.open({
                        title: "添加题目",
                        type: 2,
                        area: ["90%", "90%"],
                        maxmin: true,
                        content: "<?=Url::toRoute(['question/create'])?>?subject_id=" + data["id"]
                    });

                    return false;
                } else {
                    layer.msg("请确认操作");
                }


            });
        });
    </script>
<?php $this->endBlock(); ?>